_wandb:
    value:
        cli_version: 0.22.1
        e:
            cpq01q29b10oq5hh8psmmogqncb5ieof:
                codePath: final_split/transformer_final_split.py
                codePathLocal: transformer_final_split.py
                cpu_count: 128
                cpu_count_logical: 256
                cudaVersion: "12.6"
                disk:
                    /:
                        total: "3449055584256"
                        used: "2825283842048"
                email: sithumi_wickramasinghe@mymail.sutd.edu.sg
                executable: /root/miniconda/envs/tslanet/bin/python
                git:
                    commit: 9a0e90c9086d29f310a671d75a31e45422d3b48f
                    remote: https://github.com/AMAAI-Lab/MineROI-Net.git
                gpu: NVIDIA L40S
                gpu_count: 6
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 18176
                      memoryTotal: "48305799168"
                      name: NVIDIA L40S
                      uuid: GPU-933c0317-8d6b-a889-a37d-401613b3aa1b
                    - architecture: Ada
                      cudaCores: 18176
                      memoryTotal: "48305799168"
                      name: NVIDIA L40S
                      uuid: GPU-13c5542e-629f-b524-99da-2bc4ad0c99d0
                    - architecture: Ada
                      cudaCores: 18176
                      memoryTotal: "48305799168"
                      name: NVIDIA L40S
                      uuid: GPU-a90305e7-4a1f-6c14-2c85-c66bfe151a36
                    - architecture: Ada
                      cudaCores: 18176
                      memoryTotal: "48305799168"
                      name: NVIDIA L40S
                      uuid: GPU-a15cb3c9-5307-04d4-2fa7-d0a088c9bb52
                    - architecture: Ada
                      cudaCores: 18176
                      memoryTotal: "48305799168"
                      name: NVIDIA L40S
                      uuid: GPU-cdbb9188-39bd-49e6-9f47-d21de2b33bf6
                    - architecture: Ada
                      cudaCores: 18176
                      memoryTotal: "48305799168"
                      name: NVIDIA L40S
                      uuid: GPU-e12a1c20-9426-d145-5c89-41c98ac4520b
                host: 745bb97695ce
                memory:
                    total: "405355331584"
                os: Linux-6.8.0-48-generic-x86_64-with-glibc2.39
                program: /root/Mine_ROI_Net/final_split/transformer_final_split.py
                python: CPython 3.10.18
                root: ./60_reproduce_seed
                startedAt: "2025-12-02T01:13:44.154053Z"
                writerId: cpq01q29b10oq5hh8psmmogqncb5ieof
        m: []
        python_version: 3.10.18
        t:
            "1":
                - 1
                - 5
                - 53
            "2":
                - 1
                - 5
                - 53
            "3":
                - 2
                - 13
                - 16
            "4": 3.10.18
            "5": 0.22.1
            "10":
                - 20
            "12": 0.22.1
            "13": linux-x86_64
batch_size:
    value: 64
d_model:
    value: 64
dim_feedforward:
    value: 256
dropout:
    value: 0.2
epochs:
    value: 20
lr:
    value: 0.0001
nhead:
    value: 4
num_classes:
    value: 3
num_layers:
    value: 2
wd:
    value: 1e-05
weight_decay:
    value: 1e-05
